### ISSUE TITLE
Undefined offset PHP notice

### ISSUE THREAD

**Issue by pacmanito** [JWardee/wp-mail-catcher#99] opened 2021-03-22 10:31 UTC
Hi again. The plugin triggered following PHP notice:
`Undefined offset: 1 in /wp-content/plugins/wp-mail-catcher/src/Models/Mail.php on line 124`

So far I was not able to reproduce the issue.

**Comment by JWardee** [comment] 2021-03-23 09:40
Thanks for the report, when I get a chance I'll check it on my local, if I can replicate it it'll be fixed in the next update!

**Comment by JWardee** [comment] 2021-04-11 23:06
Not able to reproduce, please open another issue if you can recreate this :)

**Closed by JWardee** 2021-04-11 23:06 UTC
Labels: bug, needs-confirmation
