### ISSUE TITLE
Issue #127 Clarification

### ISSUE THREAD

**Issue by RobGH** [JWardee/wp-mail-catcher#128] opened 2022-03-27 10:47 UTC
In response to closed Issue #127.....

I'm not sure I understand your response. At present, only Email Log is installed. They have an option to delete or not delete the log when uninstalling their plugin (I will tell it to not delete the log). If I do so, leaving the email log in place, and then install WP Mail Catcher --- this is my question now --- will WP Mail Catcher be able to see and manage (i.e. resend, view, etc) what is in the log?

Our goal with changing to WP Mail Catcher is to preserve and continue managing the email logs created by Email Log, but now with WP Mail Catcher. We are hoping this will work!

**Comment by RobGH** [comment] 2022-03-27 11:35
If you don't know the answer, would it be possible to ask you to install Email Log on a test site, do something to create notification activity, change settings to not delete log when uninstalling, uninstall and then install WP Mail Catcher to see if it can see and manage the previous email notifications?

We would be forever ingratiated to you if you could do this test, saving us the trouble of having to do the same test!

**Comment by JWardee** [comment] 2022-03-27 14:40
Ah I see what you mean. No that will not work, WP Mail Catcher uses it's own database table to manage logs, so logs created by other plugins will not be compatible. As a thought you could keep both plugins activated and just use WP Mail Catcher for your logs moving forward, whilst referring to Email Log for older emails. Or store the older emails in a spreadsheet or something and just use WP Mail Catcher.

Feel free to respond to this issue rather than opening a new one - I'm only closing it because it's a query not a bug report, makes things easier for me to manage :)

**Closed by JWardee** 2022-03-27 14:40 UTC

**Comment by RobGH** [comment] 2022-03-27 15:29
Thank you James, and sorry for disturbing any structure. Yeah, we suspected this might not be do-able and with your confirmation we'll have to choose an option that will best serve us before I make the change to use WP Mail Catcher.

If we choose to keep Email Log just to see past notifications, won't that create a conflict of 2 plugins both trying to record and send notifications? Or, is the point you made associated with de-activating Email Log when not needing to view the notifications and only activating when we need to see them (and then de-activate again)?

Also, is the WP Mail Catcher team aware of any plugins that are in conflict with it? Specifically the Asgaros Forum plugin (https://www.asgaros.de/), which is one of the main purposes for our site?

**Comment by JWardee** [comment] 2022-03-29 20:22
I don't think there would be a conflict at what I would have thought would happen is you'll end up with both plugins (Email Log and WP Mail Catcher) saving a copy of out going emails, but either option you've suggested (with de-activating it and re-activating it).

WP Mail Catcher is compatible with most things, here's the list of [known compatibility and any issues](https://github.com/JWardee/wp-mail-catcher#confirmed-support) but I would recommend testing it yourself to confirm.
